FROM node:20-alpine AS base

#Stage 1: prune workspace for the API

FROM base AS builder
RUN apk update && apk add --no-cache libc6-compat

WORKDIR /app
RUN npm install -g turbo
COPY . .
RUN turbo prune api --docker

#Stage 2 : install dependencies and build

FROM base AS installer
RUN apk update && apk add --no-cache libc6-compat
WORKDIR /app

#dependencies for prune lockfile
COPY .gitignore .gitignore
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/package-lock.json ./package-lock.json
RUN npm ci

# /app
# ├── package.json
# ├── package-lock.json
# ├── apps/
# │   └── api/package.json
# └── packages/
#     └── shared/package.json

#copying the sourcecode
COPY --from=builder /app/out/full/ .

# app
# │
# ├── apps/
# │   └── api/
# │       ├── src/
# │       ├── package.json
# │       └── tsconfig.json
# │
# ├── packages/
# │   └── shared/
# │
# ├── node_modules/
# ├── package.json
# └── turbo.json

RUN npx turbo run build --filter=@media-force/api

# Entire Repository
#         │
#         ▼
# Builder Stage
#         │
#         ├── turbo prune
#         │
#         ▼
#     Pruned Repository
#         │
#         ▼
# Installer Stage
#         │
#         ├── Copy package manifests
#         ├── npm ci
#         ├── Copy source code
#         ├── turbo build
#         │
#         ▼
# Compiled dist/

RUN npm prune --omit=dev

#Stage 3 : production runner

FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production

# non-root user for security
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system -uid 1001 nestjs
USER nestjs
# i changed permission 
RUN chown -R nestjs:nodejs /app

# copying bult app and production node modules
COPY --from=installer /app .

EXPOSE 3000

CMD ["node", "apps/api/dist/main.js"]









