FROM node:22-alpine AS base
RUN npm install -g pnpm

#Stage 1: prune workspace for the API

FROM base AS builder
RUN apk update && apk add --no-cache libc6-compat

WORKDIR /app
RUN npm install -g turbo
COPY . .
RUN turbo prune @media-force/api --docker

#Stage 2 : install dependencies and build

FROM base AS installer
RUN apk update && apk add --no-cache libc6-compat
WORKDIR /app

#dependencies for prune lockfile
COPY .gitignore .gitignore
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
RUN pnpm install --frozen-lockfile



#copying the sourcecode
COPY --from=builder /app/out/full/ .


RUN pnpm exec turbo run build --filter=@media-force/api


RUN CI=true pnpm prune --prod

RUN rm -rf .turbo
RUN find apps packages -type d -name "src" -exec rm -rf {} +

#Stage 3 : production runner

FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production

# RUN apk add --no-cache yt-dlp ffmpeg
RUN apk add --no-cache python3 ffmpeg curl && \
    curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp && \
    chmod a+rx /usr/local/bin/yt-dlp

# non-root user for security
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nestjs

# i changed permission 
RUN chown -R nestjs:nodejs /app
RUN mkdir -p /app/storage && chown -R nestjs:nodejs /app/storage

USER nestjs
# copying bult app and production node modules
COPY --chown=nestjs:nodejs --from=installer /app .

EXPOSE 3000

CMD ["node", "apps/api/dist/main.js"]









