FROM node:20-alpine AS base

#stage1 - prune workspace
FROM base AS builder
RUN apk update && apk add --no-cache libc6-compat
WORKDIR /app
RUN npm install -g turbo

COPY . .

RUN turbo prune @media-force/web --docker

#stage2 - install and build

FROM base AS installer
RUN apk update && apk add --no-cache libc6-compat
WORKDIR /app

#install deps
COPY .gitignore .gitignore
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/package-lock.json ./package-lock.json
RUN npm ci

#build project
COPY --from=builder /app/out/full/ .
RUN npx turbo run build --filter=@media-force/web

#removing dev dep.
RUN npm prune --omit=dev

#stage3 runner
FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=4321

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

USER astrojs

#copy astro built app
COPY --from=installer --chown=astrojs:nodejs /app/apps/web/dist ./dist
#copy pruned node modules
COPY --from=installer --chown=astrojs:nodejs /app/node_modules ./node_modules




EXPOSE 4321

# CMD ["npm", "run", "start", "-w", "@media-force/web"]
# CMD ["node", "apps/web/.next/standalone/server.js"]

# Standalone creates its own server.js file so no need to npm to start it!
CMD ["node", "./dist/server/entry.mjs"]

