FROM node:20-alpine AS base

#stage1
FROM base AS builder
RUN apk update && apk add --no-cache libc6-compat
WORKDIR /app
RUN npm install -g turbo

COPY . .

RUN turbo prune @media-force/web --docker

#stage2

FROM base AS installer
RUN apk update && apk add --no-cache libc6-compat
WORKDIR /app

COPY .gitignore .gitignore
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/package-lock.json ./package-lock.json
RUN npm ci

COPY --from=builder /app/out/full/ .
RUN npx turbo run build --filter=@media-force/web

#removing dev dep.
RUN npm prune --omit=dev

#stage3 runner
FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production

RUN addgroup --system -gid 1001 nodejs
RUN adduser --system -uid 1001 nextjs

COPY --from=installer /app .

USER nextjs


EXPOSE 3000

# CMD ["npm", "run", "start", "-w", "@media-force/web"]
CMD ["node", "apps/web/.next/standalone/server.js"]
