name: Deploy mediaforce to Homelab

on:
    push:
        branches: ["main"]


env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ritikkumar27/media-force

jobs:
    # Job1

    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            
            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                registry: ${{env.REGISTRY}}
                username: ${{github.actor}}
                password: ${{secrets.GITHUB_TOKEN}}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push API image
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./Dockerfile.api
                push: true
                tags: |
                  ${{env.REGISTRY}}/${{env.IMAGE_NAME}}-api:latest
                  ${{env.REGISTRY}}/${{env.IMAGE_NAME}}-api:${{ github.sha }}

            - name: Build and push Web image
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./Dockerfile.web
                push: true
                tags: |
                  ${{env.REGISTRY}}/${{env.IMAGE_NAME}}-web:latest
                  ${{env.REGISTRY}}/${{env.IMAGE_NAME}}-web:${{ github.sha }}
    #job2

    deploy:
        needs: build-and-push
        runs-on: homelab mediaforce

        steps:
            - name: Pull and Deploy on Homelab
              run: |
                # -> login to ghcr because my repo is private
                echo "${{secrets.GITHUB_TOKEN}}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

                cd /srv/docker/apps/mediaforce

                docker compose pull
                docker compose up -d          